/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package database;

import database.DBConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import java.awt.Graphics;
import javax.swing.DefaultListModel;
import java.util.ArrayList;



public class GlavnaForma extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GlavnaForma.class.getName());
ArrayList<String> proizvodjaci = new ArrayList<>();

ArrayList<Integer> brojevi = new ArrayList<>();
  public void ucitajModele() {

    try {

        Connection con = DBConnection.getConnection();

        String sql = "SELECT model.ModelID, model.Naziv, proizvodjac.Naziv AS Proizvodjac " +
                     "FROM model INNER JOIN proizvodjac " +
                     "ON model.ProizvodjacID = proizvodjac.ProizvodjacID";

        PreparedStatement pst = con.prepareStatement(sql);

        ResultSet rs = pst.executeQuery();

        DefaultListModel model = new DefaultListModel();

        while(rs.next()) {

            String red = rs.getInt("ModelID") + "   "
                    + rs.getString("Naziv") + ", "
                    + rs.getString("Proizvodjac");

            model.addElement(red);
        }

        jListModeli.setModel(model);

    } catch(Exception e) {
        e.printStackTrace();
    }
}
  public void ucitajProizvodjace() {

    try {

        Connection con = DBConnection.getConnection();

        String sql = "SELECT * FROM proizvodjac";

        PreparedStatement pst = con.prepareStatement(sql);

        ResultSet rs = pst.executeQuery();

        cmbProizvodjac.removeAllItems();

        while(rs.next()) {

            cmbProizvodjac.addItem(rs.getString("Naziv"));
        }

    } catch(Exception e) {
        e.printStackTrace();
    }
}
  public void crtajGrafik() {

    Graphics g = panelGrafik.getGraphics();

    if(g == null) {
        return;
    }

    g.clearRect(0, 0,
            panelGrafik.getWidth(),
            panelGrafik.getHeight());

    int x = 30;

    for(int i = 0; i < brojevi.size(); i++) {

    int visina = brojevi.get(i) * 10;

    g.fillRect(x,
            250 - visina,
            40,
            visina);

    g.drawString(
            proizvodjaci.get(i),
            x,
            270
    );

    g.drawString(
            brojevi.get(i).toString(),
            x + 10,
            240 - visina
    );

    x += 70;
}
}
  
    public GlavnaForma() {
        initComponents();
        ucitajModele();
         ucitajProizvodjace();
          txtOdGodine.setEditor(
            new javax.swing.JSpinner.NumberEditor(
                    txtOdGodine,
                    "#"
            )
    );

    txtDoGodine.setEditor(
            new javax.swing.JSpinner.NumberEditor(
                    txtDoGodine,
                    "#"
            )
    );
         txtOdGodine.setValue(1990);

         txtDoGodine.setValue(2027);
         
    }

    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNaziv = new javax.swing.JTextField();
        btnIzmeni = new javax.swing.JButton();
        btnIzadji = new javax.swing.JButton();
        cmbProizvodjac = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtSifra = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListModeli = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtOdGodine = new javax.swing.JSpinner();
        txtDoGodine = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        txtKilometraza = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblStatistika = new javax.swing.JTable();
        panelGrafik = new javax.swing.JPanel();
        btnPrikazi = new javax.swing.JButton();
        btnIzadji2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Proizvodjac");

        jLabel2.setText("Naziv");

        btnIzmeni.setText("Izmeni");
        btnIzmeni.addActionListener(this::btnIzmeniActionPerformed);

        btnIzadji.setText("Izadji");
        btnIzadji.addActionListener(this::btnIzadjiActionPerformed);

        jLabel3.setText("Model:");

        jLabel4.setText("Sifra");

        jListModeli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListModeliMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jListModeli);

        jButton1.setText("Pretrazi");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtNaziv))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnIzmeni, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                            .addComponent(btnIzadji, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbProizvodjac, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(79, 79, 79)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtSifra, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jButton1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSifra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbProizvodjac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addComponent(btnIzmeni, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(btnIzadji, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Modeli automobila", jPanel1);

        jLabel5.setText("Godiste");

        jLabel6.setText("od:");

        jLabel7.setText("do:");

        jLabel8.setText("Kilometraza");

        tblStatistika.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Proizvodjac", "Broj"
            }
        ));
        jScrollPane3.setViewportView(tblStatistika);

        javax.swing.GroupLayout panelGrafikLayout = new javax.swing.GroupLayout(panelGrafik);
        panelGrafik.setLayout(panelGrafikLayout);
        panelGrafikLayout.setHorizontalGroup(
            panelGrafikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 368, Short.MAX_VALUE)
        );
        panelGrafikLayout.setVerticalGroup(
            panelGrafikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 311, Short.MAX_VALUE)
        );

        btnPrikazi.setText("Prikazi");
        btnPrikazi.addActionListener(this::btnPrikaziActionPerformed);

        btnIzadji2.setText("Izadji");
        btnIzadji2.addActionListener(this::btnIzadji2ActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnPrikazi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnIzadji2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)))
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtOdGodine, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                            .addComponent(txtDoGodine)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(txtKilometraza, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(panelGrafik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(txtOdGodine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(txtDoGodine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jLabel5)))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtKilometraza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(panelGrafik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrikazi)
                    .addComponent(btnIzadji2))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Broj raspolozivih vozila", jPanel2);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("APLIKACIJA SLUZI ZA PREGLED I IZMENU PODATAKA O POLOVNIM AUTOMOBILIMA.\n\nPRVI TAB:\n- Prikazuje sve modele automobila.\n- Pretraga modela vrsi se unosom sifre i klikom na dugme Pretrazi.\n- Nakon selekcije modela prikazuju se detalji o vozilu.\n- Moguce je izmeniti naziv modela i proizvodjaca.\n- Klikom na dugme Izmeni podaci se cuvaju u bazi.\n\nDRUGI TAB:\n- Prikazuje broj raspolozivih vozila po proizvodjacu.\n- Pretraga se vrsi na osnovu godista i maksimalne kilometraze.\n- Rezultati se prikazuju tabelarno i graficki.");
        jScrollPane4.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Uputstvo", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try {

    Connection con = DBConnection.getConnection();

    String sql = "SELECT model.Naziv, proizvodjac.Naziv AS Proizvodjac " +
                 "FROM model INNER JOIN proizvodjac " +
                 "ON model.ProizvodjacID = proizvodjac.ProizvodjacID " +
                 "WHERE ModelID=?";

    PreparedStatement pst = con.prepareStatement(sql);

    pst.setInt(1, Integer.parseInt(txtSifra.getText()));

    ResultSet rs = pst.executeQuery();

    if(rs.next()) {

        txtNaziv.setText(rs.getString("Naziv"));

        cmbProizvodjac.setSelectedItem(
                rs.getString("Proizvodjac")
        );

    } else {

        jListModeli.clearSelection();

        txtNaziv.setText("");

        cmbProizvodjac.setSelectedIndex(-1);

        JOptionPane.showMessageDialog(this,
                "Model ne postoji!");
    }

} catch(Exception e) {
    e.printStackTrace();
}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jListModeliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListModeliMouseClicked
        try {

    if(jListModeli.getSelectedValue() == null) {
        return;
    }

    String selektovan = jListModeli.getSelectedValue().toString();

    String id = selektovan.split(" ")[0];

    txtSifra.setText(id);

    Connection con = DBConnection.getConnection();

    String sql = "SELECT model.Naziv, proizvodjac.Naziv AS Proizvodjac " +
                 "FROM model INNER JOIN proizvodjac " +
                 "ON model.ProizvodjacID = proizvodjac.ProizvodjacID " +
                 "WHERE ModelID=?";

    PreparedStatement pst = con.prepareStatement(sql);

    pst.setInt(1, Integer.parseInt(id));

    ResultSet rs = pst.executeQuery();

    if(rs.next()) {

        txtNaziv.setText(rs.getString("Naziv"));

        cmbProizvodjac.setSelectedItem(
                rs.getString("Proizvodjac")
        );
    }

} catch(Exception e) {
    e.printStackTrace();
}
    }//GEN-LAST:event_jListModeliMouseClicked

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
        try {

    Connection con = DBConnection.getConnection();

    String naziv = txtNaziv.getText();

    String proizvodjac = cmbProizvodjac.getSelectedItem().toString();

    int proizvodjacID = 0;

    String sqlPro = "SELECT ProizvodjacID FROM proizvodjac WHERE Naziv=?";

    PreparedStatement pstPro = con.prepareStatement(sqlPro);

    pstPro.setString(1, proizvodjac);

    ResultSet rs = pstPro.executeQuery();

    if(rs.next()) {

        proizvodjacID = rs.getInt("ProizvodjacID");
    }

    String sql = "UPDATE model SET Naziv=?, ProizvodjacID=? " +
                 "WHERE ModelID=?";

    PreparedStatement pst = con.prepareStatement(sql);

    pst.setString(1, naziv);

    pst.setInt(2, proizvodjacID);

    pst.setInt(3, Integer.parseInt(txtSifra.getText()));

    int rezultat = pst.executeUpdate();

    if(rezultat > 0) {

        JOptionPane.showMessageDialog(this,
                "Uspešno izmenjeno!");

        ucitajModele();

    } else {

        JOptionPane.showMessageDialog(this,
                "Izmena nije uspela!");
    }

} catch(Exception e) {
    e.printStackTrace();
}
    }//GEN-LAST:event_btnIzmeniActionPerformed

    private void btnIzadjiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzadjiActionPerformed
       System.exit(0);
    }//GEN-LAST:event_btnIzadjiActionPerformed

    private void btnPrikaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrikaziActionPerformed
   try {

    proizvodjaci.clear();
    brojevi.clear();

    Connection con = DBConnection.getConnection();

    String sql =
            "SELECT proizvodjac.Naziv AS Proizvodjac, COUNT(*) AS Broj " +
            "FROM vozilo " +
            "INNER JOIN model ON vozilo.ModelID = model.ModelID " +
            "INNER JOIN proizvodjac ON model.ProizvodjacID = proizvodjac.ProizvodjacID " +
            "WHERE GodinaProizvodnje BETWEEN ? AND ? " +
            "AND PredjenoKM <= ? " +
            "GROUP BY proizvodjac.Naziv";

    PreparedStatement pst = con.prepareStatement(sql);

    pst.setInt(1,
            (Integer) txtOdGodine.getValue());

    pst.setInt(2,
            (Integer) txtDoGodine.getValue());

    pst.setInt(3,
            Integer.parseInt(txtKilometraza.getText()));

    ResultSet rs = pst.executeQuery();

    javax.swing.table.DefaultTableModel model =
            new javax.swing.table.DefaultTableModel();

    model.addColumn("Proizvodjac");

    model.addColumn("Broj");

    while(rs.next()) {

        String p = rs.getString("Proizvodjac");

        int b = rs.getInt("Broj");

        proizvodjaci.add(p);

        brojevi.add(b);

        model.addRow(new Object[] {
            p,
            b
        });
    }

    tblStatistika.setModel(model);

    crtajGrafik();

} catch(Exception e) {

    e.printStackTrace();
}
    }//GEN-LAST:event_btnPrikaziActionPerformed

    private void btnIzadji2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzadji2ActionPerformed
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_btnIzadji2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GlavnaForma().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzadji;
    private javax.swing.JButton btnIzadji2;
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnPrikazi;
    private javax.swing.JComboBox<String> cmbProizvodjac;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList<String> jListModeli;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel panelGrafik;
    private javax.swing.JTable tblStatistika;
    private javax.swing.JSpinner txtDoGodine;
    private javax.swing.JTextField txtKilometraza;
    private javax.swing.JTextField txtNaziv;
    private javax.swing.JSpinner txtOdGodine;
    private javax.swing.JTextField txtSifra;
    // End of variables declaration//GEN-END:variables
}
